version: 3.0.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015
configuration: RelWithDebInfo
platform: x64
clone_folder: c:\projects\mariadb-connector-c
before_build:
- cmd: >-
    cd c:\projects\mariadb-connector-c

    echo running cmake

    cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=RelWithDebInfo
build:
  project: mariadb-connector-c.sln
  parallel: true
  verbosity: minimal
